version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: scada_influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: scada_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # --- CẤU HÌNH GỬI EMAIL ---
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=phamviethuy1210@gmail.com
      - GF_SMTP_PASSWORD=kshecrmhcrckjowo
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=phamviethuy1210@gmail.com
      - GF_SMTP_FROM_NAME=SCADA Alert System
    depends_on:
      - influxdb
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: scada_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: always

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.6.1
    container_name: scada_kafka_init_topics
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # Khởi tạo topic thô với 6 partitions
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scada.raw.v1 --partitions 6 --replication-factor 1
      # Khởi tạo topic Dead Letter Queue (DLQ) với 3 partitions
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic scada.dlq.v1 --partitions 3 --replication-factor 1
      echo '===== DANH SÁCH TOPIC ĐÃ TẠO ====='
      kafka-topics --bootstrap-server kafka:29092 --list
      "
    restart: "no"

volumes:
  influxdb_data:
  grafana_data:
  kafka_data: